apiVersion: apps/v1
kind: Deployment
metadata:
    name: expressapp
spec:
    selector: 
        matchLabels:
            app: expressapp 
    replicas: 3
    template:
        metadata:
            labels:
                app: expressapp
        spec:
            containers:
            - name: expressapp
              image: dockerpanas/docker-test:19
              imagePullPolicy: Always
              
---
apiVersion: v1
kind: Service
metadata:
    name: expressapp-svc
spec:
    selector: 
        app: expressapp
    ports:
        - name: http
          port: 3000
          targetPort: 3000
    type: LoadBalancer



 