apiVersion: apps/v1
kind: Deployment
metadata:
  name: expressapp
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
    selector:
      matchLabels:
        app: expressapp
        template:
            metadata:
              labels:
                app: expressapp
            spec:
              containers:
              - image: dockerpanas/docker-test:latest
                imagePullPolicy: Always
                name: expressapp
                ports:
                - containerPort: 3000
              
---
apiVersion: v1
kind: Service
metadata:
    name: expressapp-svc
spec:
    selector: 
        app: expressapp
    ports:
        - name: http
          port: 3000
         
    type: LoadBalancer



 