apiVersion: v1
kind: Pod
metadata:
    name: expressapp
    labels: 
        app: expressapp
spec:
    containers:
         - name: expressapp
           image: dockerpanas/docker-test:19
              
---
apiVersion: v1
kind: Service
metadata:
    name: expressapp-svc
spec:
    selector: 
        app: expressapp
    ports:
        - name: http
          port: 3000
         
    type: LoadBalancer



 